version: "3.1"

services:
    db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: ovino
            POSTGRES_PASSWORD: ovino
            POSTGRES_DB: ovino_db
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "8264:5432"

volumes:
    db:
